services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
      MARIADB_USER: payment_user
      MARIADB_PASSWORD: payment_password
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "11064:3306"
